services:
  - type: web
    name: expedia-api
    runtime: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/Expedia_Abdelrahman_Alrefaie-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
